### ISSUE TITLE
Question: Mixins

### ISSUE THREAD

**Issue by havenchyk** [stylecow/stylecow#8]
Hi,

Could you clarify, how can I use mixins with stylecow and is it possible to use mixins?

Thanks

**Comment by oscarotero** [comment]
Hi, sorry but there is not a plugin for mixins in this moment.
[There is a plugin for](https://github.com/stylecow/stylecow-plugin-extend) `@extend` that uses the [syntax proposed by Tab Atkins](http://tabatkins.github.io/specs/css-extend-rule/) (implemented only with placeholder selectors), so if your mixins does not need arguments, it's a solution. Anyway, we are working to improve this plugin to use variables like this:
```css
%my-button {
    background: var(--bg-color, blue);
    color: var(--text-color, white);
}
.default-button {
    @extend %my-button;
}
.invert-button {
    --bg-color: white;
    --text-color: blue;
    @extend %my-button;
}
```
